# Generated by Django 3.0.8 on 2020-07-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0021_auto_20200724_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.PositiveIntegerField()),
                ('malzeme_adi', models.CharField(max_length=30)),
                ('birim_fiyati', models.DecimalField(decimal_places=2, max_digits=40)),
                ('Miktari', models.DecimalField(decimal_places=2, max_digits=25)),
                ('olcu_birimi', models.CharField(max_length=30)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=40)),
                ('Form333', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form3.Form3')),
            ],
        ),
    ]
