# Generated by Django 3.0.8 on 2020-07-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0022_malzeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malzeme',
            name='Miktari',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='birim_fiyati',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='sira_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='malzeme',
            name='tutar',
            field=models.CharField(max_length=30),
        ),
    ]
