# Generated by Django 3.0.8 on 2020-07-27 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0023_auto_20200725_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzeme',
            name='kimden',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='kime',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='tarih',
            field=models.DateField(default=datetime.datetime(2020, 7, 27, 8, 12, 3, 333278)),
        ),
    ]
