# Generated by Django 3.0.8 on 2020-07-27 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0024_auto_20200727_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malzeme',
            name='tarih',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
