# Generated by Django 3.0.8 on 2020-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0026_auto_20200803_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form3',
            name='isin_kategorisi',
            field=models.CharField(choices=[('ihale', 'ihale'), ('teklif', 'Teklif'), ('Malz.Tedariği', 'Malz.Tedariği'), ('Diğer', 'Diğer')], max_length=25),
        ),
    ]
