# Generated by Django 3.0.8 on 2020-08-05 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0028_auto_20200804_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form3',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
