# Generated by Django 3.0.8 on 2020-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0029_auto_20200805_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form3',
            name='Aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama           '),
        ),
    ]
