# Generated by Django 3.0.8 on 2020-08-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0030_auto_20200805_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malzeme',
            name='kimden',
        ),
        migrations.RemoveField(
            model_name='malzeme',
            name='kime',
        ),
        migrations.RemoveField(
            model_name='malzeme',
            name='tarih',
        ),
        migrations.AlterField(
            model_name='form3',
            name='Aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
    ]
