# Generated by Django 3.0.8 on 2020-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0031_auto_20200812_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzeme',
            name='kimden',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='kime',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='tarih',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
