# Generated by Django 3.0.8 on 2020-07-22 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form3', '0013_auto_20200722_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onay', models.BooleanField(default=False, verbose_name='Firma Tarafından Onay Verildi : ')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tarih', models.DateField(default=datetime.datetime(2020, 7, 22, 14, 23, 59, 557052, tzinfo=utc), verbose_name="Firma'nın Onaylama Tarihi :")),
                ('Form44', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='form3.Form3')),
            ],
        ),
    ]
