# Generated by Django 3.0.8 on 2020-07-22 14:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form4',
            name='Olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form4',
            name='tarih',
            field=models.DateField(default=datetime.datetime(2020, 7, 22, 14, 53, 9, 529332, tzinfo=utc), verbose_name="Firma'nın Onaylama Tarihi :"),
        ),
    ]
