# Generated by Django 3.0.8 on 2020-07-23 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0003_auto_20200723_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form4',
            name='onay',
            field=models.BooleanField(default=False, verbose_name='Firma adına yapacağımız hizmet tamamlandı mı ? : '),
        ),
        migrations.AlterField(
            model_name='form4',
            name='tarih',
            field=models.DateField(default=datetime.datetime(2020, 7, 23, 7, 8, 22, 434627, tzinfo=utc), verbose_name="Firma'nın Onaylama Tarihi :"),
        ),
    ]
