# Generated by Django 3.0.8 on 2020-07-24 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0008_auto_20200724_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form4',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Firma'nın Onaylama Tarihi :"),
        ),
    ]
