# Generated by Django 3.0.8 on 2020-08-05 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0009_auto_20200724_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form4',
            name='tarih',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
