# Generated by Django 3.0.8 on 2020-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firmalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmalar',
            name='firma_adresi',
            field=models.CharField(max_length=100, verbose_name='Adres'),
        ),
    ]
