# Generated by Django 3.0.8 on 2020-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firmalar', '0003_auto_20200818_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmalar',
            name='firma_adi',
            field=models.CharField(max_length=75, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='firmalar',
            name='firma_adresi',
            field=models.CharField(max_length=100, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='firmalar',
            name='firma_telefon',
            field=models.CharField(max_length=30, verbose_name='Telefon Numarası'),
        ),
    ]
