# Generated by Django 3.0.8 on 2020-08-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form3', '0032_auto_20200812_2140'),
        ('anasayfa', '0001_initial'),
        ('form4', '0011_auto_20200805_1516'),
        ('form_1', '0037_auto_20200812_1329'),
        ('form2', '0035_auto_20200805_1516'),
        ('form5', '0026_form5_onay'),
        ('Firmalar', '0005_auto_20200818_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmalar',
            name='anasayfa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anasayfa.Anasayfa'),
        ),
        migrations.AlterField(
            model_name='firmalar',
            name='form1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_1.Form1'),
        ),
        migrations.AlterField(
            model_name='firmalar',
            name='form2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form2.Form2'),
        ),
        migrations.AlterField(
            model_name='firmalar',
            name='form3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form3.Form3'),
        ),
        migrations.AlterField(
            model_name='firmalar',
            name='form4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form4.Form4'),
        ),
        migrations.AlterField(
            model_name='firmalar',
            name='form5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form5.Form5'),
        ),
    ]
