# Generated by Django 3.0.8 on 2020-08-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firmalar', '0006_auto_20200818_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmalar',
            name='anasayfa',
        ),
        migrations.RemoveField(
            model_name='firmalar',
            name='form1',
        ),
        migrations.RemoveField(
            model_name='firmalar',
            name='form2',
        ),
        migrations.RemoveField(
            model_name='firmalar',
            name='form3',
        ),
        migrations.RemoveField(
            model_name='firmalar',
            name='form4',
        ),
        migrations.RemoveField(
            model_name='firmalar',
            name='form5',
        ),
    ]
