# Generated by Django 3.0.8 on 2020-08-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firmalar', '0007_auto_20200820_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmalar',
            name='Olusturan',
        ),
    ]
