# Generated by Django 3.0.7 on 2020-07-14 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 7, 55, 31, 109924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='form1',
            name='dosya',
            field=models.FileField(db_index=True, upload_to=''),
        ),
    ]
