# Generated by Django 3.0.7 on 2020-07-14 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0002_auto_20200714_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 8, 26, 5, 91993, tzinfo=utc)),
        ),
    ]
