# Generated by Django 3.0.8 on 2020-07-15 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0004_auto_20200715_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 14, 21, 54, 134108, tzinfo=utc)),
        ),
    ]
