# Generated by Django 3.0.8 on 2020-07-15 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0005_auto_20200715_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 15, 46, 30, 192642, tzinfo=utc)),
        ),
    ]
