# Generated by Django 3.0.8 on 2020-07-16 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0008_auto_20200716_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 8, 45, 37, 990051, tzinfo=utc)),
        ),
    ]
