# Generated by Django 3.0.8 on 2020-07-17 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0009_auto_20200716_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='iptal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 13, 54, 28, 10399, tzinfo=utc)),
        ),
    ]
