# Generated by Django 3.0.8 on 2020-07-17 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0010_auto_20200717_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 14, 0, 51, 656591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='form1',
            name='dosya',
            field=models.FileField(blank=True, db_index=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='form1',
            name='iptal',
            field=models.BooleanField(default=False, verbose_name='İptal Et'),
        ),
    ]
