# Generated by Django 3.0.8 on 2020-07-21 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0018_auto_20200721_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 15, 47, 47557, tzinfo=utc)),
        ),
    ]
