# Generated by Django 3.0.8 on 2020-07-21 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0020_auto_20200721_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 14, 33, 39, 295148, tzinfo=utc)),
        ),
    ]
