# Generated by Django 3.0.8 on 2020-07-24 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0031_auto_20200724_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
