# Generated by Django 3.0.8 on 2020-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0032_auto_20200724_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='ilgili_birim',
            field=models.CharField(choices=[('Sağlık', 'Sağlık'), ('OSGB', 'OSGB'), ('Diğer', 'Diğer')], max_length=25, verbose_name='İlgili Birim        '),
        ),
        migrations.AlterField(
            model_name='form1',
            name='isin_kategorisi',
            field=models.CharField(choices=[('ihale', 'ihale'), ('teklif', 'Teklif'), ('Malz.Tedariği', 'Malz.Tedariği'), ('Diğer', 'Diğer')], max_length=25, verbose_name='Yapılan İşin Kategorisi       '),
        ),
        migrations.AlterField(
            model_name='form1',
            name='konusu',
            field=models.TextField(verbose_name='Konu ile ilgili Açıklama         '),
        ),
        migrations.AlterField(
            model_name='form1',
            name='sorumlu_kisi',
            field=models.CharField(choices=[('cengiz bey', 'Cengiz Bey'), ('tekin bey', 'Tekin Bey'), ('ilhan bey', 'İlhan Bey'), ('mustafa bey', 'Mustafa Bey'), ('diğer', 'Diğer')], max_length=25, verbose_name='İşten Sorumlu Kişi        '),
        ),
    ]
