# Generated by Django 3.0.8 on 2020-08-08 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0034_auto_20200808_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='form1',
            name='bitis',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
