# Generated by Django 3.0.8 on 2020-08-08 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0035_auto_20200808_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='baslangic',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='form1',
            name='bitis',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
