# Generated by Django 3.0.8 on 2020-08-20 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0037_auto_20200812_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='FirmaAdi',
            field=models.CharField(choices=[('Hekimbey A.Ş', 'Hekimbey A.Ş'), ('OrBy Bilişim Sistemleri A.Ş', 'OrBy Bilişim Sistemleri A.Ş')], default=django.utils.timezone.now, max_length=60, verbose_name='Fiarma Adı'),
            preserve_default=False,
        ),
    ]
