# Generated by Django 3.0.8 on 2020-08-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firmalar', '0008_remove_firmalar_olusturan'),
        ('form_1', '0038_form1_firmaadi'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='Firmaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Firmalar.Firmalar'),
        ),
    ]
