# Generated by Django 3.0.8 on 2020-08-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0039_form1_firmaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='FirmaAdi',
            field=models.CharField(choices=[('Hekimbey A.Ş', 'Hekimbey A.Ş'), ('OrBy Bilişim Sistemleri A.Ş', 'OrBy Bilişim Sistemleri A.Ş')], max_length=60, verbose_name='Firma Adı'),
        ),
    ]
