# Generated by Django 3.0.8 on 2020-08-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0043_auto_20200820_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='FirmaAdi',
            field=models.CharField(choices=[('Hekimbey A.Ş', 'Hekimbey A.Ş'), ('Labotest Diagnostik Sistemler A.Ş', 'Labotest Diagnostik Sistemler A.Ş'), ('OrBy Bilişim Sistemleri A.Ş', 'OrBy Bilişim Sistemleri A.Ş')], max_length=60, verbose_name='Firma Adı'),
        ),
    ]
