# Generated by Django 3.0.8 on 2020-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_1', '0045_auto_20200820_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='FirmaAdi',
            field=models.CharField(choices=[('Abdioğulları Ambalaj ve San.Tic.Ltd.Şti', 'Abdioğulları Ambalaj ve San.Tic.Ltd.Şti'), ('Hekimbey A.Ş', 'Hekimbey A.Ş'), ('IT Services Adana', 'IT Services Adana'), ('Labotest Diagnostik Sistemler A.Ş', 'Labotest Diagnostik Sistemler A.Ş'), ('OrBy Bilişim Sistemleri A.Ş', 'OrBy Bilişim Sistemleri A.Ş'), ('Rahatoğlu İnşaat A.Ş', 'Rahatoğlu İnşaat A.Ş'), ('Yıldırım Ticaret A.Ş', 'Yıldırım Ticaret A.Ş')], max_length=60, verbose_name='Firma Adı'),
        ),
    ]
