# Generated by Django 3.0.8 on 2020-08-17 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_1', '0037_auto_20200812_1329'),
        ('form4', '0011_auto_20200805_1516'),
        ('form5', '0026_form5_onay'),
        ('form3', '0032_auto_20200812_2140'),
        ('form2', '0035_auto_20200805_1516'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anasayfa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_1.Form1')),
                ('form2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form2.Form2')),
                ('form3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form3.Form3')),
                ('form4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form4.Form4')),
                ('form5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form5.Form5')),
            ],
        ),
    ]
