# Generated by Django 3.0.8 on 2020-08-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anasayfa',
            name='form1',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='form2',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='form3',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='form4',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='form5',
        ),
    ]
