# Generated by Django 3.0.8 on 2020-08-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_auto_20200820_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anasayfa',
            name='Olusturan',
        ),
    ]
