# Generated by Django 3.0.8 on 2020-07-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='odemePeriyodu',
            field=models.PositiveIntegerField(blank=1, verbose_name='Ödeme Periyodu'),
        ),
    ]
