# Generated by Django 3.0.8 on 2020-07-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0004_form5_bugun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='dosya',
            field=models.FileField(db_index=True, null=True, upload_to='', verbose_name='Fatura PDF Ekleyiniz.'),
        ),
    ]
