# Generated by Django 3.0.8 on 2020-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0005_auto_20200724_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='dosya',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to='', verbose_name='Fatura PDF Ekleyiniz.'),
        ),
    ]
