# Generated by Django 3.0.8 on 2020-07-24 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0006_auto_20200724_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='dosya',
            field=models.FileField(blank=True, db_index=True, default=datetime.datetime(2020, 7, 24, 11, 30, 42, 203784, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
