# Generated by Django 3.0.8 on 2020-07-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0008_auto_20200724_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='dosya',
            field=models.FileField(db_index=True, upload_to='files/', verbose_name='Fatura PDF Ekleyiniz.'),
        ),
    ]
