# Generated by Django 3.0.8 on 2020-07-25 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0009_auto_20200724_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='bugun',
            field=models.DateField(default=datetime.date(2020, 7, 25)),
        ),
    ]
