# Generated by Django 3.0.8 on 2020-07-27 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0010_auto_20200725_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='bugun',
            field=models.DateField(default=datetime.date(2020, 7, 27)),
        ),
    ]
