# Generated by Django 3.0.8 on 2020-07-27 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0012_auto_20200727_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='bugun',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
