# Generated by Django 3.0.8 on 2020-07-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0013_auto_20200727_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='bugun',
            field=models.DateField(auto_now_add=True),
        ),
    ]
