# Generated by Django 3.0.8 on 2020-07-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0014_auto_20200728_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form5',
            name='bugun',
        ),
    ]
