# Generated by Django 3.0.8 on 2020-07-28 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0015_remove_form5_bugun'),
    ]

    operations = [
        migrations.AddField(
            model_name='form5',
            name='bugun',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
