# Generated by Django 3.0.8 on 2020-07-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0016_form5_bugun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='odemePeriyodu',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ödeme Periyodu'),
        ),
        migrations.AlterField(
            model_name='form5',
            name='tarih',
            field=models.DateField(blank=True, null=True, verbose_name=' Varsa Ödeme Periyodu Biteceği Tarih'),
        ),
    ]
