# Generated by Django 3.0.8 on 2020-08-05 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form5', '0017_auto_20200729_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='faturaVade',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fatura Vadesi'),
        ),
        migrations.AlterField(
            model_name='form5',
            name='tarih',
            field=models.DateTimeField(blank=True, null=True, verbose_name=' Varsa Ödeme Periyodu Biteceği Tarih'),
        ),
    ]
