# Generated by Django 3.0.7 on 2020-07-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_1', '0003_auto_20200714_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AtanmaTarihi', models.DateTimeField(auto_created=True, verbose_name='Oluşturma Tarihi')),
                ('Sorumlusu', models.CharField(choices=[('orhunakar', 'Orhun Akar'), ('orhunakar01', 'Orhun Akar'), ('Deneme', 'Deneme Deneme')], max_length=25, verbose_name='Sorumlu Kişiyi Ata')),
                ('Aciklama', models.TextField(verbose_name='Açıklama')),
                ('Form2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form_1.Form1')),
            ],
        ),
    ]
