# Generated by Django 3.0.8 on 2020-07-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0002_auto_20200715_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='AtanmaTarihi',
            field=models.DateTimeField(auto_created=True, verbose_name='Atanma Tarihi'),
        ),
    ]
