# Generated by Django 3.0.8 on 2020-07-15 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form2', '0003_auto_20200715_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='Olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form2',
            name='Sorumlusu',
            field=models.CharField(choices=[('orhunakar', '')], max_length=25, verbose_name='Sorumlu Kişiyi Ata'),
        ),
    ]
