# Generated by Django 3.0.8 on 2020-07-17 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0007_auto_20200717_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='AtanmaTarihi',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 7, 17, 14, 0, 51, 665631, tzinfo=utc), verbose_name='Atanma Tarihi'),
        ),
    ]
