# Generated by Django 3.0.8 on 2020-07-21 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0015_auto_20200721_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='AtanmaTarihi',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 7, 21, 12, 15, 47, 63153, tzinfo=utc), verbose_name='Atanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='Sorumlusu',
            field=models.CharField(choices=[('orhunakar', 'orhunakar')], max_length=25, verbose_name='Sorumlu Kişiyi Ata'),
        ),
    ]
