# Generated by Django 3.0.8 on 2020-07-23 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0026_auto_20200723_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='AtanmaTarihi',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 7, 23, 11, 40, 50, 663947, tzinfo=utc), verbose_name='Atanma Tarihi'),
        ),
    ]
