# Generated by Django 3.0.8 on 2020-07-24 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0028_auto_20200724_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='AtanmaTarihi',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Atanma Tarihi'),
        ),
    ]
