# Generated by Django 3.0.8 on 2020-07-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0030_auto_20200727_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='Sorumlusu',
            field=models.CharField(choices=[('orhunakar', 'orhunakar'), ('yetkisiz', 'yetkisiz')], max_length=25, verbose_name='Sorumlu Kişiyi Ata'),
        ),
    ]
