# Generated by Django 3.0.8 on 2020-07-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0031_auto_20200727_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='Sorumlusu',
            field=models.CharField(choices=[('adana', 'adana'), ('orhunakar', 'orhunakar'), ('yetkisiz', 'yetkisiz')], max_length=25, verbose_name='Sorumlu Kişiyi Ata'),
        ),
    ]
