# Generated by Django 3.0.8 on 2020-08-05 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0032_auto_20200728_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='AtanmaTarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Olusturma Tarihi'),
        ),
    ]
