# Generated by Django 3.0.8 on 2020-08-05 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0033_auto_20200805_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='AtanmaTarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
